name: Context testing
on: 
  workflow_dispatch:

jobs:
  dump_contexts_to_log:
    runs-on: ubuntu-latest
    steps:
      - name: Dump GitHub context
        env:
          GITHUB_CONTEXT: ${{ toJson(github) }}
        run: echo "$GITHUB_CONTEXT"
      - name: pr title
        env: 
          TITLE: ${{ github.event.pull_request.title }}
          P_ID: "${TITLE:0:2}"
          
        run: |
          echo P_ID: "$P_ID" 
          echo "Title: $TITLE" 
          PID="${TITLE:0:2}" 
          echo "new pid $PID" 
          which tr
          PID2=$(echo $PID | tr '[:upper:]' '[:lower:]') 
          echo "new pid2 $PID2" 

     # - name: Dump job context
     #   env:
     #     JOB_CONTEXT: ${{ toJson(job) }}
     #   run: echo "$JOB_CONTEXT"
     # - name: Dump steps context
     #   env:
     #     STEPS_CONTEXT: ${{ toJson(steps) }}
     #   run: echo "$STEPS_CONTEXT"
     # - name: Dump runner context
     #   env:
     #     RUNNER_CONTEXT: ${{ toJson(runner) }}
     #   run: echo "$RUNNER_CONTEXT"
     # - name: Dump strategy context
     #   env:
     #     STRATEGY_CONTEXT: ${{ toJson(strategy) }}
     #   run: echo "$STRATEGY_CONTEXT"
     # - name: Dump matrix context
     #   env:
     #     MATRIX_CONTEXT: ${{ toJson(matrix) }}
     #   run: echo "$MATRIX_CONTEXT"
      
