name: check only own files have been changed

on:
  workflow_dispatch:

jobs:
  check-own-folder:
    runs-on: ubuntu-latest
    steps:
    - name: vars
      run: |
        echo "some github variables:" \
        echo $GITHUB_REF  \
        echo "sha: ${{ github.event.head_commit.sha }}" \
        echo "message: ${{ github.event.head_commit.message }}" \
        echo "pr commit sha: ${{ github.event.pull_request.head.sha }}" \
        echo "pr commit ref: ${{ github.event.pull_request.head.ref }}" \
        echo "pr commit message: ${{ github.event.pull_request.head.message }}" \
        echo "pr commit: ${{ github.event.pull_request.head }}" \
        echo "base ref: ${{ github.event.pull_request.base.ref }}" \
        echo "base sha: ${{ github.event.pull_request.base.sha }}" 

    - uses: actions/checkout@v4
      with:
        fetch-depth: 0
        submodules: false

    - name: "diff commit"
      run: |
          git status
          echo "files changed: " 
          git diff --name-only ${{ github.event.head_commit.sha }}
      continue-on-error: true
      
    - name: "diff pr"
      continue-on-error: true
      run: |
        echo "files changed: "
        git diff --name-only ${{ github.event.pull_request.head.sha }}

    - name: "diff base head"
      continue-on-error: true
      run: |
        echo "files changed: "
        git diff --name-only ${{ github.event.pull_request.base.sha }} ${{ github.event.pull_request.head.sha }}


    - name: "git base head grep"
      continue-on-error: true
      run: |
        git diff --name-only ${{ github.event.pull_request.base.sha }} ${{ github.event.pull_request.head.sha }} | grep -v ss24 

    - name: "git diff main with check"
      continue-on-error: true
      run: |
         if [[ "" != $(git diff --name-only ${{ github.event.pull_request.base.sha }} ${{ github.event.pull_request.head.sha }} | grep -v ss24) ]]; then 
                echo "more files changed than allowed:"
                git diff --name-only main | grep -v ss24
            else
                echo "all good"
         fi