name = "Showtime 2021"
description = "Theme for presenting the IMI showtime projects"
min_version = "0.72.0"

[[authors]]
  name = "Tobi Hoffmann"
  homepage = "tobihoffmann.com"
  
[[authors]]
  name = "Luis Hankel"
  homepage = "https://kaes3kuch3n.de"
