name: PR Hugo Deploy

on:
  pull_request:

  workflow_dispatch:

jobs:
  build:
    if: github.repository == 'htw-imi-showtime/showtime-website'
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
      with:
        submodules: false
    - name: Get Theme
      run: |
        git submodule update --init themes/showtime-theme-2021

    - name: Hugo setup
      uses: peaceiris/actions-hugo@v3
      with:
        hugo-version: '0.128.0'
        extended: true

    - name: Build
      run: |
        hugo \
          --environment staging \
          --baseURL "https://htw-imi-showtime.github.io/tryout/" \
          --buildDrafts 

    - name: "Upload artifact"
      uses: actions/upload-artifact@v4
      with:
        name: hugo_site
        path: public

# see https://docs.github.com/en/actions/using-workflows/storing-workflow-data-as-artifacts
  deploy:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: "pr number"
        run: |
          echo ${{ github.event.number }}
      - name: Download a single artifact
        uses: actions/download-artifact@v4
        with:
          name: hugo_site
      - name: ls
        run: |
          ls public
          tree
          
