name: PR Hugo Build

on:

  workflow_dispatch:

jobs:
  build:
    if: github.repository == 'htw-imi-showtime/showtime-website'
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
      with:
        submodules: false
    - name: Get Theme
      run: |
        git submodule update --init themes/showtime-theme-2021

    - name: Hugo setup
      uses: peaceiris/actions-hugo@v3
      with:
        hugo-version: '0.128.0'
        extended: true

    - name: Build
      run: |
        hugo \
          --environment staging \
          --baseURL "https://htw-imi-showtime.github.io/tryout/" \
          --buildDrafts 
   